#**Getting started with numpy**

In [5]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [6]:
import numpy
a=numpy.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [9]:
import numpy as np
print(np.__version__)

1.18.5


Create a numpy, ndarray object

In [10]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [11]:
import numpy as np
a=np.array([345])
print(a)
print(type(a))

[345]
<class 'numpy.ndarray'>


In [13]:
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)
print(type(a))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>


In [14]:
import numpy as np
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a)
print(type(a))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>


In [16]:
import numpy as np

a=np.array(456)
b=np.array([1,2,3,4,5,6,7])
c=np.array([[1,2,3,4,5],[6,7,8,9,10]])
d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [17]:
import numpy as np

a=np.array([1,2,3,4,5,6,7])
print(a[0])

1


In [18]:
import numpy as np

a=np.array([1,2,3,4,5,6,7])
print(a[2]+a[4])

8


In [19]:
import numpy as np

a=np.array([1,2,3,4,5,6,7])
print(a[:])

[1 2 3 4 5 6 7]


In [20]:
import numpy as np

a=np.array([1,2,3,4,5,6,7])
print(a[0:6])

[1 2 3 4 5 6]


In [21]:
import numpy as np

a=np.array([1,2,3,4,5,6,7])
print(a[-2])

6


In [23]:
import numpy as np

a=np.array([1,2,3,4,5,6,7])
print(a[-4:-2])

[4 5]


In [29]:
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)
print('5th element on 2nd dimension is',a[1,4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
5th element on 2nd dimension is 10


In [34]:
import numpy as np
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a)
print(a[0,1,2],'th element in 1 st dimension is',a[0,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6 th element in 1 st dimension is 6


In [35]:
import numpy as np
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a)
print('3rd element in 1 st dimension is',a[0,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3rd element in 1 st dimension is 6


In [36]:
import numpy as np
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a)
print('last element in 1 st dimension is',a[1,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
last element in 1 st dimension is 12


In [39]:
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)
print('last element in 2 nd dimension is',a[1,4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
last element in 2 nd dimension is 10


In [42]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a[1:6])

[2 3 4 5 6]


In [45]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a[1:(6+1)])

[2 3 4 5 6 7]


In [46]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a[1:5])

[2 3 4 5]


In [47]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a[5:])

[ 6  7  8  9 10]


In [48]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a[:5])

[1 2 3 4 5]


In [49]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a[:-1])

[1 2 3 4 5 6 7 8 9]


In [50]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a[:-5])

[1 2 3 4 5]


In [51]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a[-3:-1])

[8 9]


In [52]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a[5:])

[ 6  7  8  9 10]


In [53]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a[1:5:2])

[2 4]


In [55]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a[1:5:3])

[2 5]


In [56]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a[:5])

[1 3 5 7 9]


In [58]:
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [59]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a.dtype)

int64


In [60]:
import numpy as np
a=np.array(['madhu','sai','mansi','payal','ashwini','rahul'])
print(a.dtype)

<U7


In [61]:
import numpy as np
a=np.array([1.1,2.2,3.3,4.4,5.5,6.6,7.7,8.8,9.9,10.10])
print(a.dtype)

float64


In [62]:
import numpy as np
a=np.array([1.1,2.2,3.3,4.4,5.5,6.6,7.7,8.8,9.9,10.10])
b=a.astype(int)
print(b)
print(b.dtype)

[ 1  2  3  4  5  6  7  8  9 10]
int64


In [63]:
import numpy as np
a=np.array([1.10,2.9,3.8,4.7,5.6,6.5,7.4,8.3,9.2,10.1])
b=a.astype(int)
print(b)
print(b.dtype)

[ 1  2  3  4  5  6  7  8  9 10]
int64


In [64]:
import numpy as np
a=np.array([1.1,2.2,3.3,4.4,5.5,6.6,7.7,8.8,9.9,10.10])
b=a.astype(bool)
print(b)
print(b.dtype)

[ True  True  True  True  True  True  True  True  True  True]
bool


In [69]:
import numpy as np
a=np.array([1.1,2.2,3.3,4.4,5.5,6.6,7.7,8.8,9.9,10.10])
b=a.copy()
print(a)
print(b)
print(b.dtype)

[ 1.1  2.2  3.3  4.4  5.5  6.6  7.7  8.8  9.9 10.1]
[ 1.1  2.2  3.3  4.4  5.5  6.6  7.7  8.8  9.9 10.1]
float64


In [71]:
import numpy as np
a=np.array([1.1,2.2,3.3,4.4,5.5,6.6,7.7,8.8,9.9,10.10])
b=a.view()
b[0]=34
print(a)
print(b)
print(b.dtype)

[34.   2.2  3.3  4.4  5.5  6.6  7.7  8.8  9.9 10.1]
[34.   2.2  3.3  4.4  5.5  6.6  7.7  8.8  9.9 10.1]
float64


In [72]:
import numpy as np
a=np.array([1.1,2.2,3.3,4.4,5.5,6.6,7.7,8.8,9.9,10.10])
b=a.copy()
b[0]=34
print(a)
print(b)
print(b.dtype)

[ 1.1  2.2  3.3  4.4  5.5  6.6  7.7  8.8  9.9 10.1]
[34.   2.2  3.3  4.4  5.5  6.6  7.7  8.8  9.9 10.1]
float64


In [74]:
import numpy as np
a=np.array([1.1,2.2,3.3,4.4,5.5,6.6,7.7,8.8,9.9,10.10])
b=a.view()#prints a value of the base attribute to check if an array owns its data or not
c=a.copy()# in this case it will not own te data, because it is a copy 
print(b.base)
print(c.base)

[ 1.1  2.2  3.3  4.4  5.5  6.6  7.7  8.8  9.9 10.1]
None


In [75]:
import numpy as np
a=np.array([1.1,2.2,3.3,4.4,5.5,6.6,7.7,8.8,9.9,10.10])
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a.shape)
print(b.shape)

(10,)
(2, 5)


In [82]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b=a.reshape(4,3)
print(b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [83]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b=a.reshape(2,3,2)
print(b)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
